apiVersion: v1
kind: Service
metadata:
  labels:
    service: grpc-api
  name: grpc-api
spec:
  ports:
  - name: "5003"
    port: 5003
    targetPort: 5003
    nodePort: 30033
  selector:
    service: grpc-api
  type: NodePort
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    service: grpc-api
  name: grpc-api
spec:
  replicas: 1
  selector:
    matchLabels:
      service: grpc-api
  template:
    metadata:
      labels:
        service: grpc-api
    spec:
      containers:
      - image: nesspll/udaconnect-grpc:latest
        name: grpc-api
        imagePullPolicy: Always
        env:
        - name: DB_USERNAME
          valueFrom:
            configMapKeyRef:
              name: db-env
              key: DB_USERNAME
        - name: DB_PASSWORD
          valueFrom:
            secretKeyRef:
              name: db-secret
              key: DB_PASSWORD
        - name: DB_NAME
          valueFrom:
            configMapKeyRef:
              name: db-env
              key: DB_NAME
        - name: DB_HOST
          valueFrom:
            configMapKeyRef:
              name: db-env
              key: DB_HOST
        - name: DB_PORT
          valueFrom:
            configMapKeyRef:
              name: db-env
              key: DB_PORT
      restartPolicy: Always